FORMAT: 1A
HOST: https://iot-soil-moisture-sensor.herokuapp.com/

# soil-moisture-sensor

IOT soil moisture sensor. Sends information about specific house on 
demand, identified by houseid. 
    
    Returned sensor fields are: 
        "sensorValue" : number value measured by sensor
        "houseid" : id of the sensor, which measured this sensorValue
        "available" : true _ if sensor is available, or false otherwise. 
    
We simulate sensor availability by random. Time after time we choose 
randomly, whether this sensor is available afterwards or not. 

## Ping [/ping]

Ping service, simply returns 200 status code

+ Response 200 (application/json)

## Get Sensor Value [/house/{houseid}]

houseid is string, identifier of the house.

### get one house sensor value [GET]

If sensor is available returns with status code `200` and a `sensorValue`.
If sensor is not available, service returns `404` without any body

+ Response 200 (application/json)

        {
            "sensorValue" : 10.25,
            "houseId" : "c637a8eb-5c1e-46fc-9de8-607df60df27a",
            "available" : true
        }
       
+ Response 404 (application/json)

## Post sensor value [/house/{houseid}/]
houseid is string.

### put one house sensor value [POST]
If sensor value is seccessfully measured, 

## Post sensor value  (application/json)
        {
            "sensorValue": 20.12
        }

+ Response 200 (application/json)

+ Response 503 (application/json)